sudo: required
services:
  - docker

before_install:
  - docker build -t asaforon/react-test -f ./client/Dockerfile.dev ./client

after_success:
  - docker build -t asaforon/multi-client ./client
  - docker build -t asaforon/multi-nginx ./nginx
  - docker build -t asaforon/multi-server ./server
  - docker build -t asaforon/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push asaforon/multi-client
  - docker push asaforon/multi-nginx
  - docker push asaforon/multi-server
  - docker push asaforon/multi-worker
