sudo: required
services:
  - docker

before_install:
  - docker build -t oronasaf123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true oronasaf123/react-test npm test -- --coverage

after_success:
  - docker build -t oronasaf123/multi-nginx ./nginx
  - docker build -t oronasaf123/multi-client ./client
  - docker build -t oronasaf123/multi-server ./server
  - docker build -t oronasaf123/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push oronasaf123/multi-nginx
  - docker push oronasaf123/multi-client
  - docker push oronasaf123/multi-server
  - docker push oronasaf123/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: eu-west-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-1-624188022062
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
